#define KAPPA 10.0
#define STEPS 69840000
#define PERIOD 10000
#define FRAMES STEPS/PERIOD
#define NX 101
#define NY 21
#define LEN NX*NY
#define NMAX 50000
#define EPSILON 7200.0
#define a 1.0
#define RUN 10

extern int N,Nb,Nd,bondGroup[NMAX*2],dihedralGroup[NMAX*4];
//N:#particles, Nb:#bonds, Nd:#dihedrals
extern float position[NMAX*3];
extern uint32_t particleID[NMAX];
extern char particleType[3][2];
extern double bendingEner[NMAX];
extern double bondHarmonicEner[NMAX];
extern double total_DHE,total_BHE;
